language: node_js
node_js:
  - '14.15'
script:
  - npm run build

deploy:
  provider: pages
  skip-cleanup: true
  local_dir: dist
  github-token: $GITHUB_TOKEN
  target_branch: gh-pages
  on:
    branch: master